[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[build.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.80.0"
