name = "Andres Max Cactus Plus"
license = "MIT"
licenselink = "https://github.com/nodejh/hugo-theme-cactus-plus/blob/master/LICENSE.md"
description = "A remix of Cactus Plus Hugo theme"
homepage = "https://github.com/nodejh/hugo-theme-cactus-plus"
tags = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
features = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
min_version = 0.20

[author]
  name = "andresmax"
  homepage = "http://andresmax.com"

[[original]]
  name = "Cactus Plus"
  homepage = "https://github.com/nodejh/hugo-theme-cactus-plus"
  repo = "https://github.com/nodejh/hugo-theme-cactus-plus/"
